### ISSUE TITLE
Convert

### ISSUE THREAD

**Issue by amrshaheen61** [JakubMarecek/FCBConverter#1]
I want to convert xml file to bin again
@JakubMarecek

**Comment by JakubMarecek** [comment]
This is for issues, not for giving help. Ask on Resistance mod page or on Discord server.

**Comment by amrshaheen61** [comment]
@JakubMarecek 
The file gets corrupted when I convert xml to bin file

**Comment by amrshaheen61** [comment]
And the game does not read string from bin file

**Comment by amrshaheen61** [comment]
In farcry3
