### ISSUE TITLE
FCP Patch unpack & repack issues 

### ISSUE THREAD

**Issue by ramyzahran** [JakubMarecek/FCBConverter#4]
after unpacking patch.fat&dat with FCBConverter, it gives me empty files !!!!
how about edit patch.fat&dat with hex editor?
almost all files unpacked is empty
i want just to edit oasisstrings.oasis in patch.fat&dat!! how to do this??!!!
i unpack & repack without editing = CRASH too
patch overrides all dat, so if patch contains a file which is in common, then the file from patch is used
COMMON.fat&dat=NO CRASH   .....   PATCH.fat&dat=CRASH
![bandicam_2021-10-29_09-20-55-695](https://user-images.githubusercontent.com/22552505/158192991-2618efa2-67e0-4ce1-b6e2-a15b5dd961ce.png)
![Screenshot_14](https://user-images.githubusercontent.com/22552505/158193010-81be665b-dba4-4543-8a5d-9a7a39cb5405.png)

**Comment by JakubMarecek** [comment]
Primal is not supported
