### ISSUE TITLE
FCBConverter corrupts some xbt`s when extracting from DAT archives(Far Cry 6)

### ISSUE THREAD

**Issue by anrej0705** [JakubMarecek/FCBConverter#5]
Hi, I bumped into that problem when I tried extract file "boombox_01_n_mips.xbt"(I guess it is normal map, because the name contains letter "n" separated by a bottom lines) from a DAT archive. After extract and convert into DDS format, I am opening a file using xnview and I see something similar to white noise barely visible edge contours. At first I thought I did something wrong, I downloaded newest version of the FCBConverter and I repeated all steps referring to the instructions from the internet, I tried to open using photoshop, at least I check RAM for errors on my PC, but I was getting same result again and again -_- 
The problem was appearing and with other texture files - as sample a diffuse texture "fct_har_shr_haircardecho_01_u_b_mips.xbt" - I also get white noise with edge contours at the output.

Is there any way to get around the problem? 
[fc6.zip](https://github.com/JakubMarecek/FCBConverter/files/11525811/fc6.zip)
![image](https://github.com/JakubMarecek/FCBConverter/assets/56804640/41e0503f-fadf-4592-9814-af2f1586614b)

**Comment by JakubMarecek** [comment]
Hi, there is zero issues. Byte length is correct, header of XBT and DDS is also correct. I opened both files successfully.
![image](https://github.com/JakubMarecek/FCBConverter/assets/33377477/a87059c1-e748-4b1f-9630-d370c80a1d81)
![image](https://github.com/JakubMarecek/FCBConverter/assets/33377477/ba23d900-42ce-49ab-8741-e5a4a1b841f5)

**Comment by anrej0705** [comment]
Can you please give advice on how to get such files correctly? I'm sure I'm doing something wrong, but what exactly?...

Maybe it's in FCBConverterFileNames? Is there something missing? I would be grateful if you explain :D

**Comment by JakubMarecek** [comment]
I see you're using XnView, idk about the tool, but it can be outdated for DDS files. Use something newer, or maybe the best option could be [Texconv](https://github.com/Microsoft/DirectXTex/wiki/Texconv)

**Comment by anrej0705** [comment]
Just now i tried texconv which u recommend - its works! 
Many thanks!
